### ISSUE TITLE
Some fatal/syntax errors do not log

### ISSUE THREAD

**Issue by inoas** [dereuromark/CakePHP-DatabaseLog#22] opened 2017-11-15 14:15 UTC
### What I did
* I have tried using this plugin with **PHP 7.1.11 and a dedicated mysql datasource**. Basic db logging works.
* Even if I add syntax errors to my controller action, it works.
* However if I add syntax/fatal errors to my .ctp templates, it does not show up neither in the database log (nor potential file logs).

Can you confirm? Any idea why?

**Comment by dereuromark** [comment] 2017-11-15 14:27
Is that in debug mode (with exception handling to browser output) or in production mode (log only)?

**Comment by dereuromark** [comment] 2017-11-15 14:34
I cannot reproduce this for both debug and production with the documented approach.
In either way it is logged as expected for e.g.

    <?php blaaaa ($tasks as $task) { ?>

as

    [ParseError] syntax error, unexpected 'as' (T_AS), expecting ',' or ')

etc

Running on PHP7.1 (I think if you are on 5.6 this is an issue of our error handling in core).

**Comment by inoas** [comment] 2017-11-15 16:34
Even on production mode it should log, should it not?

**Comment by jcsiegrist** [comment] 2017-11-22 21:54
for me php return TypeErrors also do not log to DatabaseLog but log to default file Log.

```
function foo(string $string): string
{
   return null;
}
```

**Comment by dereuromark** [comment] 2017-11-23 00:06
Could this be the issue of the ErrorHandler? Does stepping through with a debugger yield any more info here?

**Comment by dereuromark** [comment] 2017-11-23 17:53
What PHP version are you using?
And what ErrorHandling setup?
Because in my case it also works there:

    [TypeError] Return value of App\...::foo() must be of the type string, null returned

is properly logged to DB

**Comment by dereuromark** [comment] 2017-11-23 17:55
Note that the Cake internal error handler has an issue with internal errors:
```php
try {
            if (!$rendererClassName) {
                throw new Exception("$rendererClassName is an invalid class.");
            }
            /* @var \Cake\Error\ExceptionRendererInterface $renderer */
            $renderer = new $rendererClassName($exception);
            $response = $renderer->render();
            $this->_clearOutput();
            $this->_sendResponse($response);
        } catch (Exception $e) {
            // Disable trace for internal errors.
            $this->_options['trace'] = false;
            $message = sprintf(
                "[%s] %s\n%s", // Keeping same message format
                get_class($e),
                $e->getMessage(),
                $e->getTraceAsString()
            );
            trigger_error($message, E_USER_ERROR);
        }
```
The PHP7 throwable catch part is missing here IMO.

**Comment by dereuromark** [comment] 2017-11-26 13:26
Should be fixed with https://github.com/cakephp/cakephp/pull/11462
Can someone confirm that branch of CakePHP together with PHP7 works?

**Comment by inoas** [comment] 2017-11-26 15:16
I assume cakephp/cakephp#11462 will make it into 3.5.x branch - if yes, I hope I won't forget to attempt to use this Logger again with the next 3.5.x release and report back on low level errors, such as syntax.

**Closed** 2017-11-26 15:45 UTC
Labels: bug
